import { UnitData } from './types';

export const RAIO_DATA: UnitData[] = [
  { id: 1, localidade: "ACARAÚ", opm_raio: "2ºPEL/5ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 2, localidade: "ACOPIARA", opm_raio: "1ºPEL/2ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 3, localidade: "AMONTADA", opm_raio: "3ºPEL/1ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 4, localidade: "AQUIRAZ", opm_raio: "1ºPEL/3ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 5, localidade: "ARACATI", opm_raio: "2ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 6, localidade: "BARBALHA", opm_raio: "2ºPEL/1ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 7, localidade: "BATURITÉ", opm_raio: "2ºPEL/3ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 8, localidade: "BEBERIBE", opm_raio: "1ºPEL/2ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 9, localidade: "BELA CRUZ", opm_raio: "2ºPEL/4ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 10, localidade: "BOA VIAGEM", opm_raio: "3ºPEL/3ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 11, localidade: "BREJO SANTO", opm_raio: "5ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 12, localidade: "CAMOCIM", opm_raio: "4ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 13, localidade: "CANINDÉ", opm_raio: "3ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 14, localidade: "CASCAVEL", opm_raio: "2ºPEL/3ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 15, localidade: "CAUCAIA", opm_raio: "1ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 16, localidade: "CRATÉUS", opm_raio: "4ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 17, localidade: "CRATO", opm_raio: "1ºPEL/1ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 18, localidade: "EUSÉBIO", opm_raio: "3ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 19, localidade: "FORTALEZA", opm_raio: "1ºBPRAIO", btl_raio: "1ºBPRAIO" },
  { id: 20, localidade: "GRANJA", opm_raio: "1ºPEL/4ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 21, localidade: "GUARACIABA DO NORTE", opm_raio: "4ºPEL/2ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 22, localidade: "HORIZONTE", opm_raio: "4ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 23, localidade: "ICAPUÍ", opm_raio: "2ºPEL/2ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 24, localidade: "ICÓ", opm_raio: "2ºPEL/2ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 25, localidade: "IGUATU", opm_raio: "2ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 26, localidade: "IPU", opm_raio: "1ºPEL/4ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 27, localidade: "IPUEIRAS", opm_raio: "2ºPEL/4ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 28, localidade: "ITAITINGA", opm_raio: "2ºPEL/4ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 29, localidade: "ITAPAJÉ", opm_raio: "1ºPEL/5ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 30, localidade: "ITAPIPOCA", opm_raio: "5ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 31, localidade: "ITAREMA", opm_raio: "3ºPEL/5ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 32, localidade: "JAGUARIBE", opm_raio: "3ºPEL/1ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 33, localidade: "JAGUARUANA", opm_raio: "3ºPEL/2ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 34, localidade: "JARDIM", opm_raio: "4ºPEL/1ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 35, localidade: "JUAZEIRO DO NORTE", opm_raio: "1ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 36, localidade: "LAVRAS DA MANGABEIRA", opm_raio: "3ºPEL/1ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 37, localidade: "LIMOEIRO DO NORTE", opm_raio: "1ºPEL/1ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 38, localidade: "MARACANAÚ", opm_raio: "2ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 39, localidade: "MARANGUAPE", opm_raio: "1ºPEL/2ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 40, localidade: "MASSAPÊ", opm_raio: "1ºPEL/1ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 41, localidade: "MAURITI", opm_raio: "1ºPEL/5ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 42, localidade: "MISSÃO VELHA", opm_raio: "2ºPEL/5ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 43, localidade: "MOMBAÇA", opm_raio: "2ºPEL/3ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 44, localidade: "MORADA NOVA", opm_raio: "2ºPEL/1ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 45, localidade: "NOVA RUSSAS", opm_raio: "3ºPEL/4ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 46, localidade: "PACAJUS", opm_raio: "1ºPEL/4ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 47, localidade: "PACATUBA", opm_raio: "2ºPEL/2ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 48, localidade: "PARACURU", opm_raio: "3ºPEL/1ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 49, localidade: "PARAIPABA", opm_raio: "4ºPEL/1ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 50, localidade: "PARAMBU", opm_raio: "1ºPEL/3ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 51, localidade: "PEDRA BRANCA", opm_raio: "4ºPEL/3ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 52, localidade: "PENTECOSTE", opm_raio: "4ºPEL/5ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 53, localidade: "QUIXADÁ", opm_raio: "3ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 54, localidade: "QUIXERAMOBIM", opm_raio: "1ºPEL/3ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 55, localidade: "RUSSAS", opm_raio: "1ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 56, localidade: "SANTA QUITÉRIA", opm_raio: "1ºPEL/3ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 57, localidade: "SANTANA DO ACARAÚ", opm_raio: "2ºPEL/1ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 58, localidade: "SÃO BENEDITO", opm_raio: "2ºPEL/2ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 59, localidade: "SÃO GONÇALO DO AMARANTE", opm_raio: "1ºPEL/1ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 60, localidade: "SOBRAL", opm_raio: "1ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 61, localidade: "TABULEIRO DO NORTE", opm_raio: "4ºPEL/1ªCIA/3ºBPRAIO", btl_raio: "3ºBPRAIO" },
  { id: 62, localidade: "TAUÁ", opm_raio: "3ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 63, localidade: "TIANGUÁ", opm_raio: "2ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 64, localidade: "TRAIRI", opm_raio: "2ºPEL/1ªCIA/2ºBPRAIO", btl_raio: "2ºBPRAIO" },
  { id: 65, localidade: "UBAJARA", opm_raio: "3ºPEL/2ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" },
  { id: 66, localidade: "VÁRZEA ALEGRA", opm_raio: "3ºPEL/2ªCIA/5ºBPRAIO", btl_raio: "5ºBPRAIO" },
  { id: 67, localidade: "VIÇOSA DO CEARÁ", opm_raio: "1ºPEL/2ªCIA/4ºBPRAIO", btl_raio: "4ºBPRAIO" }
];